"""Add proof jobs and verification tables

Revision ID: a19b8135e96c
Revises: 172411ac4b1d
Create Date: 2025-10-16 00:57:41.829539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19b8135e96c'
down_revision: Union[str, None] = '172411ac4b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proof_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_data_hash', sa.String(length=64), nullable=False),
    sa.Column('output_data_hash', sa.String(length=64), nullable=True),
    sa.Column('input_data_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='proofstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('proof_path', sa.String(length=500), nullable=True),
    sa.Column('witness_path', sa.String(length=500), nullable=True),
    sa.Column('settings_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_jobs_celery_task_id'), 'proof_jobs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_proof_jobs_id'), 'proof_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_proof_jobs_model_id'), 'proof_jobs', ['model_id'], unique=False)
    op.create_index(op.f('ix_proof_jobs_status'), 'proof_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_proof_jobs_user_id'), 'proof_jobs', ['user_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proof_job_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('verification_time_ms', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.ForeignKeyConstraint(['proof_job_id'], ['proof_jobs.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    op.create_index(op.f('ix_verifications_model_id'), 'verifications', ['model_id'], unique=False)
    op.create_index(op.f('ix_verifications_proof_job_id'), 'verifications', ['proof_job_id'], unique=False)
    op.create_index(op.f('ix_verifications_verifier_id'), 'verifications', ['verifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_verifier_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_proof_job_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_model_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_proof_jobs_user_id'), table_name='proof_jobs')
    op.drop_index(op.f('ix_proof_jobs_status'), table_name='proof_jobs')
    op.drop_index(op.f('ix_proof_jobs_model_id'), table_name='proof_jobs')
    op.drop_index(op.f('ix_proof_jobs_id'), table_name='proof_jobs')
    op.drop_index(op.f('ix_proof_jobs_celery_task_id'), table_name='proof_jobs')
    op.drop_table('proof_jobs')
    # ### end Alembic commands ###
